添加npm包Linux下的手册页，更新README，写注释
Clipteam/clipcc-extension-cli pull request #1
Opened 2021-09-02 08:16 UTC by fengshuo2004

作出了如上所述的小更改，代码已通过测试

2021-09-03 17:00 UTC, alexcui03 requested changes
1. `.gitignore` 请使用与包名无关的通配
2. `README.md` 中 Develop 板块存在错误, 请使用 yarn, Fork 的东西不要乱扔谢谢
3. 大注释请使用 jsdoc, 别人的代码不需要你自作聪明随意添加注释, 不应修改不必要修改的代码或与当前 Pull Request 无关的代码
4. 不需要 man page
5. 不得修改 `package.json` 中 `version` 字段
6. 不得存在任何与 Pull Request 描述不符的修改

2021-09-03 17:03 UTC, sparrowhe commented on cli.js
> +// 定义了没调用，这是啥
R U Kidding Me??

2021-09-03 17:05 UTC, sparrowhe commented
这个PR可能存在较多的问题需要修改，所以我把它转成草稿。

2021-09-04 03:52 UTC, SinanGentoo requested changes

2021-09-04 03:52 UTC, SinanGentoo commented on cli.js
> +        // 回显执行的命令，青色
```suggestion
        // 回显执行的命令，青色
```
没必要注释到这种程度吧

2021-09-04 03:52 UTC, SinanGentoo commented on cli.js
> +        return author.split(',').map(v => v.trim());
滚去用三元

2021-09-04 03:52 UTC, SinanGentoo commented on cli.js
> +        choices: ['javascript', 'typescript' /*, 'coffeescript'*/]
？

2021-09-06 20:27 UTC, fengshuo2004 commented
好的，这个PR你们随便处理。如果司南愿意改动后merge也没问题，不然的话我按照要求改改，下次会支持coffeescript语言扩展。短一点的条件判断用三元运算符写OK，像 `copyFilesToDir()` 那个绝对不该用三元，用了又没有缩进特别难看懂。

2023-06-01 03:30 UTC, closed without merging